import type { NextPage } from 'next';
import Head from 'next/head';
import { PostCreateTemplate } from '../../../components/templates/PostsCreateTemplate';

const Page: NextPage = () => {
  console.log('create');

  return (
    <div>
      <Head>
        <title>Create</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>メイン</main>
      <PostCreateTemplate />
    </div>
  );
};

export default Page;
