import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { createPost, getPosts } from '../firebase/posts';
import styles from '../styles/Home.module.css';

import { Post } from '../types/post';

const Page: NextPage = () => {
  const [posts, setPosts] = useState<Post[]>([]);
  console.log(posts);

  useEffect(() => {
    (async () => {
      const response = await getPosts();
      setPosts(response);
    })();
  }, []);

  const handleCreatePost = async () => {
    const post = await createPost({
      title: 'test',
      body: 'body',
    });
    console.log(post);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 onClick={handleCreatePost}>記事投稿テスト</h1>
        {posts.map((post) => (
          <div key={post.id}>{post.title}</div>
        ))}
      </main>

      <footer className={styles.footer}>
        <p>フッター</p>
      </footer>
    </div>
  );
};

export default Page;
